print("Введите вид питомца")
view = input()
print("Введите возраст питомца")
age = input()
print("Введите кличку питомца")
name = input()
print("Это", view, "по кличке", name, "Возраст:", age, "года.")